### ISSUE TITLE
not display the column, If use Japanese in channel name.

### ISSUE THREAD

**Issue by inoue4u** [blue0513/slackdeck-proto#32] opened 2019-06-24 08:03 UTC

**Comment by munierujp** [comment] 2019-06-24 11:23
Maybe, you can use channnel id (like `CXXXXXXXX`) instead of channel name.
Isn't it? @blue0513

**Comment by blue0513** [comment] 2019-06-24 12:12
@munierujp Thx. Ah, I didn't check the case of Japanese channel name... But as you said, using channel id is one of the solutions

**Comment by blue0513** [comment] 2019-06-24 12:19
But, of course, we should make implementation to allow users to open the channel, even writing Japanese channel names in `settings.json`.

**Comment by blue0513** [comment] 2019-06-26 13:33
@inoue4u Sorry I couldn't reproduce this problem. Is the step correct?

## Step
1. set the channel's name as "日本語のチャンネル" in `settings.json`
2. npm start
3. I could open "日本語のチャンネル" in one of the columns

```json
{
    "url": "https://foo-bar.slack.com/",
    "other_urls": [
        "https://foo-bar.slack.com/"
    ],
    "contents": [
        {
            "channel": "日本語のチャンネル",
            "style": "body-only",
            "width": "large-tab"
        }
    ]
}
```

**Comment by inoue4u** [comment] 2019-06-27 01:02
@blue0513 
The step is correct.
I show you reproducable setting below.

``` json
{
    "url": "https://something.slack.com/",
    "contents": [
        {
            "channel": "channel",
            "style": "body-only",
            "width": "large-tab"
        },
        {
            "channel": "otherchannel",
            "style": "body-only",
            "width": "large-tab"
        },
        {
            "channel": "開発プロジェクト報告会",
            "style": "body-only",
            "width": "large-tab"
        }
    ]
}
```

**Comment by blue0513** [comment] 2019-06-30 08:05
@inoue4u Thx! hmm...it looks the correct format and character code is not bad.

Could you open `DeveloperTool` in electron?
1. launch app by `npm start`
2. press `Cmd + shift + i` (if you don't use Mac, maybe the key-bind is not this)
3. open `Console` tab like below
4. reload app by `Cmd + r` (if you don't use Mac, maybe the key-bind is not this)

Then if you see any errors, plz tell me what the message is.

<img width="500" alt="Screen Shot 2019-06-30 at 17 01 36" src="https://user-images.githubusercontent.com/8979468/60394035-dbe29e00-9b58-11e9-899b-6ae75467bb0b.png">

**Comment by blue0513** [comment] 2019-07-07 13:27
Unfortunately, it couldn't be reproduced. I'll close this issue but when anyone reproduce this problem, please re-open this issue again :+1:

**Closed by blue0513** 2019-07-07 13:27 UTC
Labels: enhancement
